# Generated by Django 3.2.5 on 2021-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('subject', models.TextField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(max_length=250, verbose_name='Message')),
            ],
        ),
    ]
